os: linux
dist: trusty
jdk: oraclejdk8
language: ruby
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - curl
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
install:
  - gem install coveralls-lcov
script:
  - flutter doctor -v
  - make
after_success:
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info

deploy:
  # validating branch master for deploying
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh && rm -rf scripts/ && pub publish -n -v
    on:
      branch: master
  # deploy tagged to pub server
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh && rm -rf scripts/ && pub publish -f -v
    on:
      tags: true