name: flutter_beacon
description: Flutter plugin for scanning beacon (iBeacon platform) devices on Android and iOS.
version: 0.2.1
author: Alann Maulana <alann.maulana@outlook.com>
homepage: https://github.com/alann-maulana/flutter_beacon

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutterbeacon
    pluginClass: FlutterBeaconPlugin
