name: Coverage Coverage Report

on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

jobs:
  codecov_io:
    name: "Codecov.io"
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'
          channel: 'stable'
      - name: Generate coverage report
        run: flutter test --coverage --coverage-path ./coverage/lcov.info
      - name: Send to codecov.io
        run: bash <(curl -s https://codecov.io/bash)
      - run: ls -al ./coverage
      - name: "Upload coverage"
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ./coverage
  
  coveralls_io:
    name: "Coveralls.io"
    needs: codecov_io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Download coverage"
      uses: actions/download-artifact@v1
      with:
        name: coverage
        path: ./coverage
    - name: "Setup ruby"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install coveralls-lcov
    - run: cat ./coverage/lcov.info
    - name: Send to coveralls.io
      run: coveralls-lcov --verbose --repo-token $COVERALLS_TOKEN coverage/lcov.info
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
